### ISSUE TITLE
您好，dynamic_evaluate函数为什么出现在训练前面呢？

### ISSUE THREAD

**Issue by 787629504** [Liuyang829/testMSDNet#1]
您好，我想问一下，在main.py文件中，dynamic_evaluate(model, test_loader, val_loader, args)的目的是什么呀？他为什么在训练迭代的前面呢？

**Comment by Liuyang829** [comment]
dynamic_evaluate只在测试的时候使用 用来进行动态推理 在结束完推理后就直接return了。在args中写了evalmode就代表是测试阶段

**Comment by 787629504** [comment]
> dynamic_evaluate只在测试的时候使用 用来进行动态推理 在结束完推理后就直接return了。在args中写了evalmode就代表是测试阶段

谢谢您的回复，那为什么这句代码会在train的前面呢？不是很理解，希望得到您的帮助。

**Comment by Liuyang829** [comment]
只有训练的时候会执行这个函数 执行完这个函数整个程序也就结束了。训练的时候又不会执行这个函数，所以写在它前面还是后面都无所谓啊，关键看执行时候的顺序喽

**Comment by 787629504** [comment]
感谢您的帮助，对于动态推理的过程，我的理解是：训练过程中，args.evalmode设置成None，会训练、验证整个网络without early exit；在测试的时候，args.evalmode设置为dynamic，会验证阈值，测试动态推理模型的性能。您看我的理解对吗？如果没有针对前几个block的分类器做训练，前面block的分类器性能会变得糟糕吗？

**Comment by Liuyang829** [comment]
你的理解是对的，在训练的时候是没有提前退出的，loss也是依据每一个分类器结果计算出来的所以肯定是每个分类器都进行了训练。没有对前几个block训练那前几个分类器的结果我觉得肯定会糟糕的吧

**Comment by 787629504** [comment]
明白了，非常感谢您的回答！
